pipelines:
  default:
    - step:
        image: node:14.15.5-alpine3.10
        caches:
          - node
        name: Run linter and tests
        script:
          - cp .env.dist .env
          - npm install
          - npm run lint
          - npm run coverage

  pull-requests:
    '**':
      - step: 
          name: build and install
          image: cypress/browsers:node14.17.0-chrome88-ff89
          caches:
            - node
            - cypress
            - npm
          script:
            - cp .env.dist .env
            - npm install
            - npm run build:ci
            - cd e2e && npm install && cd ..
          artifacts:
            - build/**
            - e2e/node_modules/**
      - parallel:
        - step:
            name: e2e - firefox
            image: cypress/browsers:node14.17.0-chrome88-ff89
            caches:
              - node
            script:
              - cp .env.e2e.dist ./e2e/.env
              - npm run e2e:ci:firefox
        - step:
            name: e2e - chrome
            image: cypress/browsers:node14.17.0-chrome88-ff89
            caches:
              - node
            script:
              - cp .env.e2e.dist ./e2e/.env
              - npm run e2e:ci:chrome

definitions:
  caches:
    cypress: ~/.cache/Cypress
    npm: ~/.npm