pipelines:
  default:
    - step:
        image: node:12.14.1
        caches:
          - node
        name: Run linter and tests
        script:
          - cp .env.dist .env
          - npm install
          - npm run lint
          - npm run coverage

  pull-requests:
    '**':
      - step: 
          name: build and install
          image: jakubmusik/cypress-e2e-runner:latest
          caches:
            - node
            - cypress
            - cypress-node
          script:
            - cp .env.dist .env
            - npm install
            - npm run build:ci
            - cd e2e && npm install && cd ..
          artifacts:
            - build/**
            - e2e/node_modules/**
      - parallel:
        - step:
            name: e2e - firefox
            image: jakubmusik/cypress-e2e-runner:latest
            caches:
              - node
            script:
              - cp .env.e2e.dist ./e2e/.env
              - npm run e2e:ci:firefox
        - step:
            name: e2e - chrome
            image: jakubmusik/cypress-e2e-runner:latest
            caches:
              - node
            script:
              - cp .env.e2e.dist ./e2e/.env
              - npm run e2e:ci:chrome
        - step:
            name: e2e - edge
            image: jakubmusik/cypress-e2e-runner:latest
            caches:
              - node
            script:
              - cp .env.e2e.dist ./e2e/.env
              - npm run e2e:ci:edge

definitions:
  caches:
    cypress: $HOME/.cache/Cypress
    cypress-node: ./e2e/node_modules